### ISSUE TITLE
XamlParseException tritt bei Programmstart auf

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#1]
System.Windows.Markup.XamlParseException ist aufgetreten.
  HResult=-2146233087
  LineNumber=12
  LinePosition=10
  Message=Zeilennummer "12" und Zeilenposition "10" von "Durch den Aufruf des Konstruktors für Typ "DidiDerDenker.BirdsEyeView.Client.ViewModels.BirdsEyeViewInterfaceViewModel", der den angegebenen Bindungseinschränkungen entspricht, wurde eine Ausnahme ausgelöst.".
  Source=PresentationFramework
  StackTrace:
       bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
  InnerException: 
       Class=14
       ErrorCode=-2146232060
       HResult=-2146232060
       LineNumber=65536
       Message=An attempt to attach an auto-named database for file C:\Users\curth\Source\Repos\DidisYT-Manager\DidisYT-Manager\DidiDerDenker.BirdsEyeView.Database\DD_DATABASE.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.
       Number=15350
       Procedure=""
       Server=(LocalDB)\MSSQLLocalDB
       Source=.Net SqlClient Data Provider
       State=1
       StackTrace:
            bei System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
            bei System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
            bei System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
            bei System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            bei System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
            bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
            bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
            bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
            bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
            bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
            bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
            bei System.Data.SqlClient.SqlConnection.Open()
            bei DidiDerDenker.BirdsEyeView.Database.DatabaseConnection.TestConnection() in C:\Users\Vogel\Source\Repos\DidisYT-Manager\DidisYT-Manager\DidiDerDenker.BirdsEyeView.Database\DatabaseConnection.cs:Zeile 57.
            bei DidiDerDenker.BirdsEyeView.Database.DatabaseConnection..ctor(String connectionString) in C:\Users\Vogel\Source\Repos\DidisYT-Manager\DidisYT-Manager\DidiDerDenker.BirdsEyeView.Database\DatabaseConnection.cs:Zeile 29.
            bei DidiDerDenker.BirdsEyeView.Database.DatabaseConnection..ctor() in C:\Users\Vogel\Source\Repos\DidisYT-Manager\DidisYT-Manager\DidiDerDenker.BirdsEyeView.Database\DatabaseConnection.cs:Zeile 22.
            bei DidiDerDenker.BirdsEyeView.Database.DatabaseConnection.get_Default() in C:\Users\Vogel\Source\Repos\DidisYT-Manager\DidisYT-Manager\DidiDerDenker.BirdsEyeView.Database\DatabaseConnection.cs:Zeile 43.
            bei DidiDerDenker.BirdsEyeView.Client.ViewModels.BirdsEyeViewInterfaceViewModel..ctor() in C:\Users\Vogel\Source\Repos\DidisYT-Manager\DidisYT-Manager\DidisYT-Manager\ViewModels\BirdsEyeViewInterfaceViewModel.cs:Zeile 22.
       InnerException:

**Comment by JonasCurth** [comment]
@DidiDerDenker Ich kann das Problem bei mir auf dem Laptop nicht nachvollziehen, habe das Projekt gerade zum ersten mal offen, gebaut und es läuft.
