### ISSUE TITLE
Datum vor der Anzeige des Titels im Task-Bereich

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#30]
Das Datum des jeweiligen Videos soll im Task-Bereich vor dem vollständig ausformulierten Folgentitel auftauchen, z.B.

01.01.2018: Let's Play Battlefield 1 [Deutsch] #000 Test

**Comment by JonasCurth** [comment]
@DidiDerDenker  Schlichtweg: Nein, da du das selbst in der Formatierung angeben kannst. **Aber** kopieren zum Einfügen bei Youtube kann dann in beiden Fällen nicht mehr realisiert werden.

**Comment by DidiDerDenker** [comment]
@JonasCurth Wofür definiere ich denn dann Anforderungen? :D
Ich brauche das Datum vor dem Folgentitel. Geht das oder geht das nicht? Wenn ja bitte auch jeden Fall einbauen. Geht es vielleicht als Tooltip? Da würde mir das Datum schon reichen

**Comment by JonasCurth** [comment]
@DidiDerDenker Wie gesagt, kannst du das über die Formatierung in der DB lösen, dort kannst du jede Variable angeben und die wird dann so angezeigt, wie du das möchtest. Im Tooltip ist es möglich, aber dann wird wahrscheinlich wieder der Fall eintreten, dass nicht der gesamte Titel angezeigt wird, kann es aber probieren.

**Comment by DidiDerDenker** [comment]
@JonasCurth Ist es möglich, die Struktur das aktuellen Tooltips auch auf die Zeile als solches anzuwenden? Fänd ich noch ein kleines Stückchen besser :)
