### ISSUE TITLE
"Heute"-Button beim Hauptkalender einfügen

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#31]
"Heute"-Button beim Hauptkalender einfügen (z.B. zwischen den beiden Arrows links neben dem Monat), um damit auf die aktuell laufende Woche zu springen.

**Comment by JonasCurth** [comment]
@DidiDerDenker  Aktuell nicht möglich, da das Element "eingekauft" ist. Mit viel Aufwand ist das möglich, ob das aber nötig ist, ist fraglich, da man ja auch über den anderen Kalender zum Aktuellen Datum kommt?

**Comment by DidiDerDenker** [comment]
@JonasCurth Ja das ist gewünscht und sogar nötig. Sonst hätte ich es ja nicht so formuliert :P
Aber ist nicht schlimm, wenn es jetzt noch nicht geht. Daher das "Mittel"-Tagging.

**Comment by JonasCurth** [comment]
@DidiDerDenker  ich denke, dass ist noch nicht mal bis dahin realisierbar, da ich die komplette Schedule-Oberfläche dafür überschreiben muss.
