### ISSUE TITLE
Format-DDL in der Eingabemaske ist ungeordnet

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#33]
Format-DDL in der Eingabemaske wie folgt ordnen:
- Let's Play
- Didi TV
- Best of

**Comment by JonasCurth** [comment]
@DidiDerDenker  Also Desc ordnen und damit genau gegenteilig zur Projekt DDL?

**Comment by DidiDerDenker** [comment]
@JonasCurth Mir egal wie, aber es soll am Ende die Reihenfolge wie oben angegeben angezeigt werden (LP -> DD -> BO)

**Comment by DidiDerDenker** [comment]
@JonasCurth Wieder geöffnet, da Let's Play zwar standardweise ausgewählt ist, aber beim Öffnen der DDL die alte Reihenfolge besteht.
