### ISSUE TITLE
Löschen-Button in Eingabemaske

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#37]
Man soll die Funktion haben, neben "Abbrechen" und "Speichern" auch das Video wieder löschen zu können.

**Comment by JonasCurth** [comment]
@DidiDerDenker  Wozu soll die Funktion an der Stelle gut sein? Über entf oder später rechtsklick kann der Eintrag auch entfernt werden. Wenn trotzdem gewollt, kann ich es gerne einbauen.

**Comment by DidiDerDenker** [comment]
@JonasCurth Ja, bitte die drei Buttons unten in die Eingabemaske packen. Also "Abbrechen", "Löschen", "Speichern"
