### ISSUE TITLE
Refresh-Button im Task-Bereich

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#45]
Refresh-Button in Task-Bereich einbinden, um die Datenbank-Verbindung aktualisieren zu können.

**Comment by JonasCurth** [comment]
@DidiDerDenker wozu? In der Datenbank wird doch nichts außerhalb des Programms geändert?

**Comment by DidiDerDenker** [comment]
@JonasCurth Habe es gerade beim Testen gemerkt, dass nicht alles aktualisiert wird. Zum Beispiel bei dem Fall mit dem doppelten Speichern. Erst sieht alles gut aus, nach dem Neustart hat man auf einmal zwei Appointments. Irgendwas muss also meiner Meinung nach aktualisiert werden, weil es immer erst nach dem Neustart gelöscht oder hinzugefügt wurde (im Fall der doppelten Hinzufügungen und Löschen über Abbrechen). Das normale Hinzufügen wird wie erwartet sofort sichtbar.
