### ISSUE TITLE
Eingabemaske öffnen (verschiedene Varianten)

### ISSUE THREAD

**Issue by DidiDerDenker** [JonasCurth/BirdsEyeView#8]
1. Klick auf "Video planen" im Hauptmenü löst das Öffnen der Eingabemaske mit
   entsprechenden Voreinstellungen aus
2. Doppelklick auf Zeile im Task-Bereich löst das Öffnen der Eingabemaske aus
3. Doppelklick auf Kalendereintrag zu einem Video löst das Öffnen der Eingabemaske aus

**Comment by JonasCurth** [comment]
@DidiDerDenker Punkt 2: Doppelklick löst aktuell das öffnen zum Bearbeiten aus, dass ist damit gemeint ja?

**Comment by DidiDerDenker** [comment]
@JonasCurth Jo :)
